{% set name = "arelle-release" %}
{% set version = "2.37.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9d80195d348fef2325886b955586f370e1f264c997fa8508f49400483df1ba2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arelleCmdLine = arelle.CntlrCmdLine:main
    - arelleGUI = arelle.CntlrWinMain:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }},<3.14
    - bottle >=0.13,<0.14
    - certifi
    - filelock
    - isodate ==0.*
    - lxml >=4,<6
    - numpy >=1,<3
    - openpyxl ==3.*
    - pillow >=10,<12
    - pyparsing ==3.*
    - python-dateutil ==2.*
    - regex

test:
  imports:
    - arelle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://arelle.org
  dev_url: https://github.com/Arelle/Arelle
  doc_url: https://arelle.org/arelle/documentation/
  summary: >
    Arelle is an end-to-end open source XBRL platform, which provides the XBRL community with an easy to use set of tools. It supports XBRL and its extension features in an extensible manner. It does this in a compact yet robust framework that can be used as a desktop application and can be integrated with other applications
    and languages utilizing its web service.
  license: Apache-2.0
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
    - aaroncameron-wk
    - allenbross-wf
    - austinmatherne-wk
    - derekgengenbacher-wf
    - stevenbronson-wk
